### ISSUE TITLE
secure config values

### ISSUE THREAD

**Issue by ulpian** [alacrity-law/apollo-test-app#2]
https://github.com/alacrity-law/apollo-test-app/blob/702f68a5c7e2afe3dd96c2414bc0466bbc21f3f7/config/default.json#L14

I suspect this is already thought out but these values should certainly be referencing some environment variables (including the db name etc) where you can manage shared environment variables across the team with a key management service like AWS KMS.

I suspect this test app is using the `config` package, there is a file around securing config files (or parts of a configuration) - there is a good page on this https://github.com/lorenwest/node-config/wiki/Securing-Production-Config-Files

**Comment by thanpolas** [comment]
In production I'd go with this method / pattern: https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables

Creating the `config/custom-environment-variables.json` file to map config vars to local environment variables.
